Controllers films users
SemekhinV/java-filmorate pull request #3
Opened 2022-11-19 18:46 UTC by SemekhinV

Добрый вечер! все тесты работают, отправляю на проверку.

2022-11-19 18:49 UTC, SemekhinV commented
Добрый вечер! все тесты работают, отправляю на проверку.

2022-11-20 15:07 UTC, kukolev requested changes

2022-11-20 15:07 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-11-20 15:07 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName().equals("")) {                                //Проверка на пустое имя
Лучше сделать проверку так: `if (!"".equals(user.getName()))`. Тогда не будет выброшен NullPointerException, если text == null

2022-11-20 15:07 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-11-20 15:07 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/validation/UserValidationTests.java
> +    void userInvalidBirthdayTest() {
Этот тест нужно разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Хороший юнит тест состоит из трех блоков кода:

1. Подготовка данных для теста
2. Вызов тестируемого метода
3. Проверка результатов

Важно, чтобы п.2 выполнялся однократно - так будет проще понять что пошло не так, если один или несколько тестов упадут.

Подробнее о хороших практиках юнит-тестирования можно прочитать тут:  https://www.baeldung.com/java-unit-testing-best-practices

2022-11-21 07:24 UTC, SemekhinV commented
Доброе утро, внес правки по вашим требованиям, так же постарался везде табы заменить на пробелы.

2022-11-21 09:43 UTC, kukolev approved these changes

2022-11-22 18:03 UTC, merged