#3
SemekhinV/java-filmorate pull request #4
Opened 2022-12-01 15:04 UTC by SemekhinV

added friends to class Film & likes to class User

2022-12-02 11:04 UTC, kukolev requested changes

2022-12-02 11:04 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Добавлен новый лайк");
По моему здесь и в остальных частях программы будет лучше если info убрать совсем, а debug повысить до info. Дело в том, что debug обычно предназначен для отладки кода и им покрывают код очень тщательно. Info может быть полезен для другого - для разбора проблем. Например пользователь пожалуется, что ставил лайк, но он не сработал. Тогда пригодится такой лог - можно будет понять, долетел ли запрос до бэкенда и что произошло потом.

Аналогично нужно поправить в остальных случаях.

2022-12-02 11:04 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static final LocalDate DATE_BOUNDARY_VALUE = LocalDate.ofYearDay(1895, 362);
По моему лучше сделать LocalDate.of(1895,  12, 28). Так будет читаться лучше.

2022-12-02 11:04 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getReleaseDate().isBefore(DATE_BOUNDARY_VALUE)) {
Валидации лучше вынести в отдельный приватный метод. Тогда каждый метод будет отвечать за свою часть функционала и код будет проще анализировать. Код при этом может выглядеть примерно так:

```
public SomeResult someMethod(...) {
    validateSomething(...);
    // business-logic here
}

private void validateSomething(...) {
    if (/* ! check something /*) {
        throw new SomeException();
    }
}

```

Таким образом в методе someMethod визуально будет проще найти бизнес-логику, ради которой этот метод и создавался.

Также лучше поправить в других методах.

2022-12-02 11:04 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userId < 0 || userId > 1000) {
По моему это ошибка - по ТЗ нет ограничения на 1000 пользователей. Нужно поправить.

2022-12-02 11:04 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userId < 0 || userId > 1000) {
По моему это ошибка - по ТЗ нет ограничения на 1000 пользователей. Нужно поправить.

2022-12-03 15:45 UTC, SemekhinV commented
Здравствуйте, исправил все ваши замечания, спасибо за объяснение правильной структуры создания бизнес логики, запомню на будущее.

2022-12-04 19:32 UTC, kukolev approved these changes

2022-12-13 17:51 UTC, merged